### PR TITLE
Clean-up.

### PR DESCRIPTION
**Pull request by GDoronin**
- Changed all 'ReasonArgs' properties and fields to be named 'BecauseArgs'.
- Changed all 'Reason' properties and fields to be named 'Because'.
- Changed all 'reasonArgs' parameters to be named 'becauseArgs'.
- Fixed some XML-Doc comments.
- It is an additional fix for commit 688184bf8e917756e434708b20cf8005d9c7b501.

For additional information please refer the following issues and pull-requests:
`Rename reason argument in Be() to because.` #28 
`Changes all 'reason' parameters to be named 'because'` #91

### CODE REVIEW

**Comment by GDoronin** [comment]
It also makes sense to rename corresponding fields in `IAssertionContext`, `AssertionContext`, `IEquivalencyValidationContext` files.

What do you think?

**Comment by dennisdoomen** [comment]
Thanks for cleaning this up. What's with those interfaces? 

PS. build failed.

**Comment by GDoronin** [comment]
**About interfaces.**
All them have `Reason` and `ReasonArgs` properties.

https://github.com/dennisdoomen/FluentAssertions/blob/master/Src/Core/Equivalency/IEquivalencyValidationContext.cs#L13-L22

https://github.com/dennisdoomen/FluentAssertions/blob/master/Src/Core/Equivalency/AssertionContext.cs#L20-L21

https://github.com/dennisdoomen/FluentAssertions/blob/master/Src/Core/Equivalency/IAssertionContext.cs#L25-L34

And such code looks a bit discomfortable for me:

```cs
public static void ShouldAllBeEquivalentTo<T>(this IEnumerable<T> subject, IEnumerable expectation,
    Func<EquivalencyAssertionOptions<T>, EquivalencyAssertionOptions<T>> config, string because = "",
    params object[] becauseArgs)
{
    EquivalencyAssertionOptions<IEnumerable<T>> source = config(AssertionOptions.CloneDefaults<T>()).AsCollection();

    var context = new EquivalencyValidationContext
    {
        Subject = subject,
        Expectation = expectation,
        RootIsCollection = true,
        CompileTimeType = typeof (IEnumerable<T>),
        // This one
        **Reason** = because,
        **ReasonArgs** = becauseArgs
    };

    new EquivalencyValidator(source).AssertEquality(context);
}```

**Comment by GDoronin** [comment]
**About the build.**
If I understand the AppVeyor output correctly, it says the problem is with publishing the package.

Can I fix it myself?

> Everything is Ok
##teamcity[blockClosed name='Zipping up the binaries']
Executing BuildPackage at 03/02/2016 13:19:45
##teamcity[blockOpened name='Building NuGet Package']
Attempting to build package from '.nuspec'.
Successfully created package 'C:\projects\fluentassertions\Artifacts\FluentAssertions.4.2.2.nupkg'.
##teamcity[blockClosed name='Building NuGet Package']
Executing PublishToMyget at 03/02/2016 13:19:48
##teamcity[blockOpened name='Publishing NuGet Package to Myget']
Pushing   to 'https://www.myget.org/F/fluentassertions_ci/'...
Error: 3/2/2016 1:19:51 PM: 
At C:\projects\fluentassertions\build\default.ps1:154 char:4 +             & $Nuget push $package.FullName $NuGetApiKey -Source "$NuGetPushSource" +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~ [<<==>>] Exception: Failed to process request. 'Forbidden'. 
Command exited with code

**Comment by dennisdoomen** [comment]
Ah yes, my publishing API key was changed. Fixed it for you. And yes, go ahead and rename those internal properties.

**Comment by GDoronin** [comment]
Thanks.
OK, I will do it.

**Comment by GDoronin** [comment]
Just to have proper references: #28 #91

**Comment by dennisdoomen** [comment]
@GDoronin you're still on this?

**Comment by GDoronin** [comment]
@dennisdoomen Yes I am. Please wait a few more days. We just had a 4-days national holidays :)

**Comment by dennisdoomen** [comment]
No worries.

**Comment by GDoronin** [comment]
@dennisdoomen It's done.

However, one more question if you don't mind..

In the file `Core\Collections\StringCollectionAssertions.cs`, what's the purpose of `becauseArg = null` parameter?

There is `params object[] becauseArgs` parameter, so the previous one seems redundant.

Also, all other methods of this class simply call the base-class implementations, but not this.

```cs
public AndConstraint<StringCollectionAssertions> Contain(IEnumerable<string> expected, string because = null,
    object becauseArg = null,
    params object[] becauseArgs)
{
    var args = new List<object> {becauseArg};
    args.AddRange(becauseArgs);
    return base.Contain(expected, because, args.ToArray());
}
```

I've noticed this because it doesn't have matching XML param tag:
```
      Src\Core\Collections\StringCollectionAssertions.cs:113 Parameter 'becauseArg' has no matching param tag in the XML comment for FluentAssertions.Collections.StringCollectionAssertions.Contain (but other parameters do)
```

**Comment by dennisdoomen** [comment]
Aich, that looks like a merge issue. Somebody recently renamed all parameters named `reasonArgs` to `becauseArgs`.

**Comment by GDoronin** [comment]
Actually it was there before my renaming.. :)

Check for example this revision from AUG 2015:
https://github.com/dennisdoomen/FluentAssertions/blob/6f0164317df98f43c5b00583d1a9b8124c286792/Src/Core/Collections/StringCollectionAssertions.cs

**Comment by dennisdoomen** [comment]
Ah, that was you ;-)

**Comment by dennisdoomen** [comment]
Hmm, it seems that you need to rebase your changes. If you can ensure your PR ends-up as a single commit, then I can merge it right away.

**Comment by GDoronin** [comment]
Hm, it seems the recent PR introduced few merge conflicts in two files:
- Src\Core\Collections\CollectionAssertions.cs
- Src\Core\Collections\SelfReferencingCollectionAssertions.cs

I'll rebase and resolve the conflicts tomorrow.

Just to clarify.
> If you can ensure your PR ends-up as a single commit, then I can merge it right away.

Do you want me to squash my commits, right?

**Comment by dennisdoomen** [comment]
> Do you want me to squash my commits, right?

Yes!

**Comment by GDoronin** [comment]
@dennisdoomen Done.

**Pull request merged**
