### PR TITLE
BeDataContractSerializable was added

### PR DESCRIPTION
**Pull request by borismod**

### CODE REVIEW

**Comment by dennisdoomen** [comment]
You have failing unit tests.

**Comment by borismod** [comment]
These tests were failing before my changes.

**Comment by dennisdoomen** [comment]
You're right. And the PR that caused it was green... :confused:

**Comment by borismod** [comment]
@dennisdoomen could you ping me, when nuget package is published with this change?

**Comment by dennisdoomen** [comment]
@borismod [ping](https://www.nuget.org/packages/FluentAssertions/4.5.0)

**Pull request merged**
