### PR TITLE
Issue #348: Adding ability to reset event monitoring

### PR DESCRIPTION
**Pull request by somewhatabstract**
This change overhauls the event monitoring somewhat so that the `MonitorEvents` method returns an object off which tracked events can be reset. This also adds a `Reset` call to the individual event recorders too. The event monitoring setup code has been moved into an `EventMonitor` class to encapsulate things a little more cleanly. Also, calling `MonitorEvents` multiple times with different interfaces for the same object adds to the existing events being tracked.

This is to address issue #348.

### CODE REVIEW

**Comment by somewhatabstract** [comment]
Documentation changes would need to be made to cover the return value of `MonitorEvents`, the new `IEventMonitor` interface calls (`Reset`, `Attach`, and `GetEventRecorder`), and the new `Reset` method on `IEventRecorder`.

**Comment by dennisdoomen** [comment]
You've been busy ;-)

What about support for a `using` block?

**Comment by somewhatabstract** [comment]
I looked at that and found it to be unnecessary. It just didn't really add any value whatsoever. What would it actually do? What gets disposed of? I just couldn't see a useful scenario for it in the end.

**Comment by dennisdoomen** [comment]
Well, it will make the scope of monitoring really explicit. And if the monitored code crashes, the reset will automatically happen without causing side-effect on other (parallel) tests.

**Comment by somewhatabstract** [comment]
Yes, I suppose the `Dispose` would remove the event recorders for the specific monitor instead of just resetting them. That makes sense.

Would you mind if I cover that in a separate PR once this one is cleared through?

**Pull request merged**
