### PR TITLE
implemented BeOnOf for DateTime

### PR DESCRIPTION
**Pull request by jeroenpot**
Included the option for datetime to be one of specified values.

### CODE REVIEW

**Comment by jeroenpot** [comment]
Oops.. let me fix that test first :-)

**Comment by jeroenpot** [comment]
For the wiki, on this page
https://github.com/dennisdoomen/fluentassertions/wiki#dates-and-times

Include:
theDatetime.Should().BeOneOf(1.March(2010).At(22, 15), 1.February(2010));

**Comment by dennisdoomen** [comment]
Nice. But can you do the same for `DateTimeOffset`. The assertions are supposed to be symmetrical.

**Comment by jeroenpot** [comment]
Tests are running ok on local machine, but i think i found i see what the issue is.

**Comment by jeroenpot** [comment]
Ok, fixed it.
If I can find some time next week I would like to built in BeCloseToOneOf

**Pull request merged**
