### PR TITLE
Switch enum underlying type comparison to use decimal rather than long

### PR DESCRIPTION
**Pull request by msackton**
Fixes issue #467 by using decimal rather than long. I didn't see any place to add enum comparision tests so I made a new file.

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Thanks for the PR. Would you be willing to adapt the specs to use the AAA syntax and naming conventions? E.g. like https://github.com/dennisdoomen/FluentAssertions/blob/master/Tests/FluentAssertions.Shared.Specs/ComparableSpecs.cs#L57

**Comment by msackton** [comment]
Sure, I probably won't get to it today, but happy to fix the naming.

**Comment by dennisdoomen** [comment]
Hi @msackton, you've abandoned your PR?

**Comment by msackton** [comment]
Sorry, I was out of town and forgot about this. I've cleaned up the tests.

**Pull request merged**
