### PR TITLE
Usings of missing 'because' parameters added to ShouldThrowExactly method

### PR DESCRIPTION
**Pull request by pavbsu**

### CODE REVIEW

**Comment by dennisdoomen** [comment]
That's weird. I would expect a missing unit test for this.

**Comment by dennisdoomen** [comment]
@pavbsu any plans with this PR?

**Comment by pavbsu** [comment]
@dennisdoomen yes, i am going to write/update unit tests for this soon.

**Comment by pavbsu** [comment]
Done. There are no special tests for 'because' parameters of ShouldThrow method, therefore existing tests for ShouldThrowExactly were updated.

**Pull request merged**
