### PR TITLE
NumericAssertions small fix

### PR DESCRIPTION
**Pull request by GDoronin**
- NumericAssertions BePositive XML-Doc comment fixed.
- Few tests added for BePositive/BeNegative when asserting zero value.

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Thanks for the fix. Would you be willing to update those specs to match the [current style](https://github.com/dennisdoomen/fluentassertions/blob/develop/FluentAssertions.Shared.Specs/NumericAssertionSpecs.cs#L93)?

**Comment by GDoronin** [comment]
Sure, can fix specs.
Can you please provide more details?

By [current style](https://github.com/dennisdoomen/fluentassertions/blob/develop/FluentAssertions.Shared.Specs/NumericAssertionSpecs.cs#L93) you mean using  Arrange/Act/Assert sections?

Do you want me to fix spec methods I've just added to match the current style?

Should there be Arrange section or not? Since I don't arrange anything.

**Comment by dennisdoomen** [comment]
Yes, the AAA structure as well as the naming style. If you just update the new ones you added, i'll look at those others late ron.

**Comment by GDoronin** [comment]
Okay, let's keep this pull request open then.
Will update it.

Name should be something like `When_asserting_zero_value_to_be_positive_it_should_throw`?

And the last question is still unclear.
Should there be Arrange section or not? Since I don't arrange anything.

```csharp
//-----------------------------------------------------------------------------------------------------------
// Arrange
//-----------------------------------------------------------------------------------------------------------

//-----------------------------------------------------------------------------------------------------------
// Act
//-----------------------------------------------------------------------------------------------------------
Action action = () => (0).Should().BePositive();

//-----------------------------------------------------------------------------------------------------------
// Assert
//-----------------------------------------------------------------------------------------------------------
act.ShouldThrow<AssertFailedException>();
```

**Comment by dennisdoomen** [comment]
Oh sorry, no, if there's nothing to arrange, leave it out.

**Comment by GDoronin** [comment]
Migrated to AAA structure.
It only remains to rename methods.

**Comment by dennisdoomen** [comment]
Thanks. You're going to do that as well?

**Comment by GDoronin** [comment]
Yes, I will.

**Comment by GDoronin** [comment]
Renaming also has been done.

**Comment by dennisdoomen** [comment]
Thanks!

**Pull request merged**
