### PR TITLE
Upgraded to netstandard1.5

### PR DESCRIPTION
**Pull request by no1melman**
Updated from netstandard1.3 to netstandard1.5

### CODE REVIEW

**Comment by no1melman** [comment]
I was seeing if it was that simple, but I don't have the UAP stuff installed on my VS, so couldn't open those projects and build with those. It works for all the standard stuff. Maybe worth just closing this PR

**Comment by dennisdoomen** [comment]
It's not that simple. We carefully choose 1.3 so that we don't cause breaking changes for existing users.

**Comment by no1melman** [comment]
Yeah, I didn't think it was going to be that simple. Is it possible to use this in a dotnet aspnet core app that targets 1.5?

**Comment by dennisdoomen** [comment]
Sure. Libraries that target higher standards can always use lower versions.

**Comment by dennisdoomen** [comment]
So what do we do wit this?

**Comment by no1melman** [comment]
I'm not sure, shall I just close it... I would need to have all the other tools installed to be able to do the other upgrades......

**Comment by dennisdoomen** [comment]
Well, I think this will be superseded by #463

**Pull request closed without merging**
